### ISSUE TITLE
Direct Seeding and Tray Seeding: Submit Button Behavior

### ISSUE THREAD

**Issue by Shahir-47** [FarmData2/FarmData2#276]
### Description

In the Direct Seeding and Tray Seeding forms, after entering an invalid value, the submit button is correctly disabled as expected. However, when the value is corrected to a valid value, the submit button remains disabled. This issue needs to be addressed to ensure that the submit button re-enables when the value is corrected.

### Steps to Reproduce
1. Navigate to the Direct Seeding or Tray Seeding form.
2. Enter an invalid value in any required field (e.g., an invalid date or number).
3. Observe that the submit button is disabled.
4. Correct the invalid value to a valid one.

### Expected Behavior
The submit button should re-enable when a previously invalid value is corrected to a valid value.

### Actual Behavior
The submit button remains disabled even after the invalid value is corrected.

### Additional Information
Please ensure that all relevant fields are checked for validity and that the submit button updates its state accordingly.

**Comment by braughtg** [comment]
In addition, the submit and reset buttons are not disabled when the form is submitted.  The `submit` function uses the incorrect data values `disableSubmit` and `disableReset` instead of `enableSubmit` and `enableReset` to try to disable the buttons.

The `*.submission.e2e.cy.js` tests should be expanded to check this behavior.  Add the test first to ensure that it fails and then fix the code to ensure that it passes.

This should also be fixed with this Issue.
