### ISSUE TITLE
fd2-up.linux.bash does not setup proper groups

### ISSUE THREAD

**Issue by FutzMonitor** [FarmData2/FarmData2#76]
## Current Design 
When running the `./fd2-up.bash` command within the bin directory on Windows 10 with WSL2, the following error is outputted by the console: 
![image](https://github.com/FarmData2/FarmData2/assets/31524934/4d0a73c9-381e-4031-8c7f-4b430632e233)
The VNC still goes up, but you cannot open the terminal 
https://github.com/FarmData2/FarmData2/assets/31524934/3c7564a4-0dc7-48f5-949c-c2de1f2a4a2b

## Desired Design 
There needs to be a fix to the database error and an analysis as to why the vnc isn't working correctly on Windows 10 running WSL2.

**Comment by braughtg** [comment]
I suspect that this has to do with the not having the necessary groups/permissions setup for WSL.  As you review the `fd2-up.bash` script in the old FarmData2 repo you'll see that there is a good bit of work done creating groups and setting permissions.  There are group ids (GIDs) passed into the container that are then also used.  I suspect that getting all of that converted over will solve both problems.

Here are some things that you'll want to look at and understand in trying to develop a solution:
- The [`fd2-up.bash` in the old FarmData2 repo](https://github.com/DickinsonCollege/FarmData2/blob/main/docker/fd2-up.bash) has all of the code that is required to do the setup of groups and permissions.  It will just need to be adapted and the necessary parts put into the [`fd2-up.linux.bash` file](https://github.com/FarmData2/FarmData2/blob/development/bin/fd2-up.linux.bash).
- There is [code that is added to the end of the `.bashrc` file in the `fd2_dev` container](https://github.com/FarmData2/FD2-Images/blob/main/fd2dev/bashrc_addition) that ensures that the default user `fd2dev` is in the `fd2grp`.  I suspect that because the `fd2grp` doesn't exist, this is the reason that the terminal will not open.  So once that is all back in place this issue should resolve.

**Comment by JingyuMarcelLee** [comment]
@braughtg I am currently working on the [fd2-up.linux.bash](https://github.com/FarmData2/FarmData2/blob/development/bin/fd2-up.linux.bash). I will make a PR directly to this issue. The issue is just as you described. fd2grp is not defined in the Linux environment and this prevents the dev container from having correct permissions to open the terminal.

**Comment by JingyuMarcelLee** [comment]
Also I suggest  @FutzMonitor to change the issue to something fd2-up.linux.bash related for clarity.

**Comment by braughtg** [comment]
# The following steps are no longer necessary.  A new `farmos2` image has been created that includes the configuration information.  Be sure to `git pull origin development` to update to the latest version to get the updates.  Delete all old fd2 images and volumes in Docker Desktop.  Then use `bin/fd2-up.bash to get the latest versions.

The database error:
![image](https://github.com/FarmData2/FarmData2/assets/16962482/b2d76ce4-7da0-4f81-922a-a4c8cfd0043e)

is due to a missing configuration file in the farmOS image.  I will work on rebuilding that image with the appropriate configuration in place, so that it is there by default.

For now you can do the configuration manually:
- Connect to `fd2dev` container via VNC:
- Open firefox
- Visit `http://farmos` - this will take you to a configuration form.  Fill out the form as follows:
  - Check `postgresSQL`
  - Database name: `farm`
  - Database username: `farm`
  - Database password: `farm`
  - Advanced Options:
    - Host: `db`
  - Save and Continue.

After that the configuration will be set correctly.

- Run the `installDb.bash` script and choose:
  - Option 1 for the release.
  - Option 2 for the sample database.

- Once that is done you should be able to visit `http://farmos` and see the site.

There are other things that need to be done to fully setup the dev environment as well.  Those are listed in the `INSTALL.md` file in the repo.~~

**Comment by braughtg** [comment]
This is working well on my windows test machine.
